### ISSUE TITLE
Access denied StartDocumentTextDetection 

### ISSUE THREAD

**Issue by schatimo** [aws-samples/amazon-textract-textractor#1]
Hi,

when running `python3 textractor.py --documents s3://inputdatatimo/document.pdf --region us-east-1 --text` I get following error message: 

> botocore.errorfactory.AccessDeniedException: An error occurred (AccessDeniedException) when calling the StartDocumentTextDetection operation:

though I granted (full access) permissions to the IAM user for S3 and Textract.
Are there any further permissions needed to make this run?

Many thanks
schatimo

**Comment by darwaishx** [comment]
Amazon Textract is now generally available so you should be able to  access it without going through whitelisting process.
