### ISSUE TITLE
timeout when calling textractor from Lambda

### ISSUE THREAD

**Issue by bvbg1** [aws-samples/amazon-textract-textractor#178]
I tried to call textractor from Lambda with an S3 file (s3://mybucket/file1.png) as source: 
`
document = extractor.analyze_document(
	file_source=s3url,
	features=[TextractFeatures.TABLES]
)
`

Execution seems to be stopping without error message, in cloudwatch logs I get:
`Task timed out after 3.03 seconds`
I have print statements afterwards that don't get printed. 

I'm using the python-3.9 lambda layer.
What is the right way to call textractor from Lambda?

**Comment by tb102122** [comment]
Increase the timeout of your lambda function and you will most likely see that it is an error due to the AWS configuration which can’t be retrieved correctly

**Comment by bvbg1** [comment]
Thanks, it was because it could not find pandas.
