### ISSUE TITLE
Missing release of latest version for amazon-textract-prettyprinte

### ISSUE THREAD

**Issue by tb102122** [aws-samples/amazon-textract-textractor#186]
The latest version is not release to on https://pypi.org/project/amazon-textract-prettyprinter/
The master branch is already using tabulate 0.9. but the latest release still uses 0.8.10.
Can you please trigger a release since I have a version conflict since I also need to use amazon-textract-textractor 1.1.0
Thanks for your help.

**Comment by schadem** [comment]
Released prettyprinter 0.1.1 with tabulate 0.9.
