### ISSUE TITLE
KeyError: 'Geometry' raised when an empty cell found

### ISSUE THREAD

**Issue by vinyasmusic** [aws-samples/amazon-textract-textractor#195]
Hello Team 

Here is an issue I had faced while using `start_expense_analysis`

Steps to reproduce 
1. Use an Invoice PDF with multiple pages
2. Call the `document = textract.start_expense_analysis` function to analyse the PDF, use an S3 URL to do the same. 
3. When the we call `document.expense_documents` we get the aforementioned KeyError. 

I did add a debugger to the textractor package inside my virtualenv to check the values and it turns out the Geometry part was missing for a Field where the value was not present

A screenshot from the invoice in question
<img width="256" alt="image" src="https://user-images.githubusercontent.com/16731446/230007791-c5a79260-878d-4880-98fc-e4cebf756a42.png">

What could be the possible solution for this ?

**Comment by Belval** [comment]
Would you be willing to share the asset (or even just the Textract response) you used so that we are better able to reproduce the issue on our side? If so send an email to belvae[AT]amazon.com.

**Comment by ThomasDelteil** [comment]
For AnalyzeExpense (contrary to Forms API), if a key does not have a attached value, you won't get the expected bounding box where the value should be if it was there. 
Do you have a use-case for that? That's something that could be taken into account in a future release.

**Comment by liaohaofu** [comment]
Right. The current version of AnalyzeExpense (AE) won't output empty value boxes. A possible current solution is to combine Forms outputs with AE outputs to obtain empty value boxes.

**Comment by vinyasmusic** [comment]
@Belval Sorry for the delayed response. I will do that today. 

@ThomasDelteil Yes, I would ideally want an empty string as value if the value is empty in the PDF. Like in the screenshot above `PO Number` should have a value of `""` or `None` instead of erroring out because there was no bounding box present.

**Comment by vinyasmusic** [comment]
Let me test this out today. Thanks

**Comment by vinyasmusic** [comment]
Working fine. 
Closing the issue. Thanks for fixing it @Belval

**Comment by mhfarahani** [comment]
@Belval 

I am getting similar error but for "LabelDetection".

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-6-06735bc9ce69> in <module>
----> 1 textract_response.expense_documents

/opt/conda/lib/python3.7/site-packages/textractor/entities/lazy_document.py in __getattr__(self, _LazyDocument__name)
     61                 self._textract_client,
     62             )
---> 63             self._document = parse(response)
     64             if self._images is not None:
     65                 for i, page in enumerate(self._document.pages):

/opt/conda/lib/python3.7/site-packages/textractor/parsers/response_parser.py in parse(response)
    965         return parse_analyze_id_response(response)
    966     if "ExpenseDocuments" in response:
--> 967         return parser_analyze_expense_response(response)
    968     else:
    969         return parse_document_api_response(response)

/opt/conda/lib/python3.7/site-packages/textractor/parsers/response_parser.py in parser_analyze_expense_response(response)
    923         summary_fields = []
    924         for summary_field in doc["SummaryFields"]:
--> 925             summary_fields.append(create_expense_from_field(summary_field, page))
    926             summary_fields[-1].raw_object = summary_field
    927 

/opt/conda/lib/python3.7/site-packages/textractor/parsers/response_parser.py in create_expense_from_field(field, page)
    877         value_expense = Expense(
    878             bbox=BoundingBox.from_normalized_dict(
--> 879                 field["ValueDetection"]["Geometry"]["BoundingBox"], spatial_object=page
    880             ),
    881             text=field["ValueDetection"]["Text"],

KeyError: 'Geometry'
```


Would not it be appropriate to add the same fix for the "LabelDetection"? The following change would address the error:

```
if "LabelDetection" in field:
  label_expense = Expense(
      None if not "Geometry" in field["LabelDetection"] else
      bbox=BoundingBox.from_normalized_dict(
          field["LabelDetection"]["Geometry"]["BoundingBox"], spatial_object=page
      ),
      text=field["LabelDetection"]["Text"],
      confidence=field["LabelDetection"]["Confidence"],
      page=page.page_num
  )
  label_expense.raw_object = field["LabelDetection"]
 ```
