### ISSUE TITLE
New Run of the Lambda Layers Action

### ISSUE THREAD

**Issue by dannellyz** [aws-samples/amazon-textract-textractor#205]
May you run the Lambda Layers action again with the new changes for v 1.3

**Comment by Belval** [comment]
Not sure if you are able to see it but the new run has started. I'll add a trigger to run this action whenever a new release is created. 

https://github.com/aws-samples/amazon-textract-textractor/actions/runs/4743705210

**Comment by dannellyz** [comment]
You guys rock thank you! Also can verify that I ran against trp in tests and now get a 10x speed up for Textractor and its not just as fast.
