### ISSUE TITLE
S3 folder limited to one 'page' of objects

### ISSUE THREAD

**Issue by athewsey** [aws-samples/amazon-textract-textractor#22]
[In textractor.py](https://github.com/aws-samples/amazon-textract-textractor/blob/ea5019475bb71b2adb1ad880f8d48b0f2b4e932f/src/textractor.py#L65), we currently seem to hard-code a limit of 1 max pages of S3 objects when calling `S3Helper.getFileNames()` to list the objects in an S3 folder input - even though the underlying helper seems capable of pagination.

It looks from the [Boto3 doc](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.list_objects_v2) like the default page length is 1000 objects so it would only come up for pretty big jobs, but I worry it might trip some folks up as I don't think there's any obvious message to the user that this limit is being applied?

My 2 cents is that the potential detriment to user experience from having the hidden limit is worse than the potential risk of somebody pointing the script at a bigger S3 folder than they expected: Particularly because today Textractor outputs such frequent diagnostics about the number of docs it's processing, and the serial nature of the queue isn't like it's going to start pushing a massive volume through APIs before anybody can spot the problem and interrupt it... But maybe others have different perspectives?

**Comment by Belval** [comment]
As this issue is over three years old and impacts the previous version Textractor I will be closing it. Feel free to reopen if the issue persists with Textractor 1.7.5.
