### ISSUE TITLE
Calling start_document_text_detection with bytes raises TypeError 

### ISSUE THREAD

**Issue by lvieirajr** [aws-samples/amazon-textract-textractor#226]
Trying to call `start_document_text_detection` directly with a bytes object (the contents of an image) will raise a type error on:
textractor/textractor.py:270
```
if not file_source.startswith("s3://"):
```

<img width="622" alt="Screen Shot 2023-07-05 at 3 39 14 PM" src="https://github.com/aws-samples/amazon-textract-textractor/assets/283394/9b2c8b25-9784-4872-8616-c56ac5b23e0b">

You are calling the startswith on a `bytes` object but passing a string.

This should work as both the docstring and the documentation say you are allowed to pass a bytes object as the file source

**Comment by Belval** [comment]
Looking into it, seems like it should be a quick fix.

**Comment by Belval** [comment]
Version 1.3.2 should fix this issue.

**Comment by lvieirajr** [comment]
Thank you for the quick turnaround!
