### ISSUE TITLE
Upgrade version pining due to pip warning

### ISSUE THREAD

**Issue by tb102122** [aws-samples/amazon-textract-textractor#231]
during the latest install I am getting the following error

DEPRECATION: amazon-textract-pipeline-pagedimensions 0.0.8 has a non-standard dependency specifier Pillow>=9.4.*. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of amazon-textract-pipeline-pagedimensions or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

I am happy to support on the PR
I would suggest replacing e.g. ``Pillow>=9.4.*`` with ``Pillow>=9.4`` and in other where ``packageName>=x.x.*`` is used with   ``packageName>=x.x``

**Comment by schadem** [comment]
Thx, @tb102122 . Go for it and I'll merge.

**Comment by tb102122** [comment]
@schadem Why do you pin the versions for Pillow in the individual setup files to specific versions but in the main requiremnt.txt for the Dev setup it is not pinned? e.g. https://github.com/aws-samples/amazon-textract-textractor/blob/309449b109b2fd3c45a741b85e7e37b3077ebfdc/overlayer/setup.py#L10

**Comment by tb102122** [comment]
@schadem should we close the issue or keep it open due to my comment ?

**Comment by schadem** [comment]
We can close for now, there is more cleanup necessary as well. I want to upgrade all to a major 1, since they are used by many customers in prod now and we should should indicate a stable API now for example.

**Comment by schadem** [comment]
Thx again, @tb102122 !

**Comment by tb102122** [comment]
@schadem when will you be able to make the release?
