### ISSUE TITLE
I would like to be able to use textractor without a profile by passing access_key, secret_access_key instead

### ISSUE THREAD

**Issue by mariame-m** [aws-samples/amazon-textract-textractor#280]
I am using textractor on a service I run and which cannot use ~/.aws/config and ~/.aws/credentials. Instead I am storing my credentials in a secret vault. My service would pulls credentials from that vault and instantiates textractor with those (I cannot write to the local file system).
Could this be added as a feature?

**Comment by tb102122** [comment]
Why are you not setting the env vars?
That feature is build in already since the version runs like that in the lambda runtime.

**Comment by Belval** [comment]
To expand on what @tb102122 wrote, if your credentials are in the environment you can instanciate Textractor with only the `region_name` parameter. For example:

```
extractor = Textractor(profile_name="default")
```

becomes

```
extractor = Textractor(region_name="us-west-2") # Change for your region
```

If you don't have your credentials in the environment, you can add them using the Python `os` module as a workaround:

```py
import os
os.environ["AWS_ACCESS_KEY_ID"] = ""
os.environ["AWS_SECRET_ACCESS_KEY"] = ""

extractor = Textractor(region_name="us-west-2") # Change for your region
```

**Comment by mariame-m** [comment]
thanks, that's exactly what I needed!
