### ISSUE TITLE
Change of return type broke my script

### ISSUE THREAD

**Issue by aka-rabbi-inv** [aws-samples/amazon-textract-textractor#282]
In this [commit](https://github.com/aws-samples/amazon-textract-textractor/commit/371a30b9e51dcdecb1a539fddd10e5fecf766fb3), the return type change from Line object to a List[Word] has introduced a error in my script
Was that a intentional change? Just to confirm if I should update my code to account for this change

https://github.com/aws-samples/amazon-textract-textractor/blame/master/textractor/entities/key_value.py#L104

![Screenshot 2023-11-24 at 1 53 50 PM](https://github.com/aws-samples/amazon-textract-textractor/assets/87089810/bdcda114-4f25-411f-a1f7-f01fcaf87b81)

**Comment by Belval** [comment]
It is, sorry this should have been properly flagged as a breaking change.

We used to return a "fake" Line object but this caused an issue because Keys are not bound to a single line so the words could be wrongly reordered.
