### ISSUE TITLE
PrettyPrinter error with csv output

### ISSUE THREAD

**Issue by noefingway** [aws-samples/amazon-textract-textractor#284]
Seeing the following error on some PDF documents:

Traceback (most recent call last):
  File "/Users/chaz/Projects/aws/extract-testing/launcher.py", line 91, in <module>
    main()
  File "/Users/chaz/Projects/aws/extract-testing/launcher.py", line 84, in main
    launcher.run_app(args['filename'], args['outputfile'])
  File "/Users/chaz/Projects/aws/extract-testing/launcher.py", line 51, in run_app
    layout_csv = get_layout_csv_from_trp2(trp2_doc)
  File "/Users/chaz/Projects/aws/extract-testing/lib/python3.9/site-packages/textractprettyprinter/t_pretty_print_layout.py", line 306, in get_layout_csv_from_trp2
    trp2_doc.get_block_by_id(id) for id in layout_block_rel.ids if layout_block_rel.ids
AttributeError: 'NoneType' object has no attribute 'ids'

Similar documents are working correctly, I'm getting a usable csv file.

Tested with  "get_text_from_layout_json", which correctly dumps the text of the document that fails in the "get_layout_csv_from_trp2".

Documents are sample radiology reports.

**Comment by noefingway** [comment]
It appears the problem is caused by no relationships for the LAYOUT_FIGURE type.

As a temporary fix I added a check for 'None' after line 304 of t_pretty_print_layout.py:

            elif layout_block.id not in processed_ids:
                layout_block_rel = layout_block.get_relationships_for_type()
                # ceb - bug fix
                if layout_block_rel is None:
                    logger.info ('layout_block_rel is None: %s', layout_block)
                    continue
                layout_blocks = [
                    trp2_doc.get_block_by_id(id) for id in layout_block_rel.ids if layout_block_rel.ids
                ]

Dump of the Tblock causing the problem:
INFO       2023-11-25 11:07:00,315 textractprettyprinter.t_pretty_print_layout get_layout_csv_from_trp2             307 : layout_block_rel is None: TBlock(geometry=TGeometry(bounding_box=TBoundingBox(width=0.19528213143348694, height=0.08578834682703018, left=0.28226974606513977, top=0.2836810350418091), polygon=[TPoint(x=0.28226974606513977, y=0.2839899957180023), TPoint(x=0.477417528629303, y=0.2836810350418091), TPoint(x=0.4775518774986267, y=0.3691641688346863), TPoint(x=0.2823990285396576, y=0.36946940422058105)]), id='c4784664-2e08-4262-bb64-c31ab28499c5', block_type='LAYOUT_FIGURE', relationships=None, confidence=74.4140625, text=None, column_index=None, column_span=None, entity_types=None, page=2, row_index=None, row_span=None, selection_status=None, text_type=None, custom=None, query=None)
INFO       2023-11-25 11:07:00,316 textractprettyprinter.t_pretty_print_layout get_layout_csv_from_trp2             307 : layout_block_rel is None: TBlock(geometry=TGeometry(bounding_box=TBoundingBox(width=0.19465941190719604, height=0.08595860749483109, left=0.5059463381767273, top=0.2838287949562073), polygon=[TPoint(x=0.5059463381767273, y=0.28413674235343933), TPoint(x=0.7004653215408325, y=0.2838287949562073), TPoint(x=0.7006057500839233, y=0.36948320269584656), TPoint(x=0.5060817003250122, y=0.36978742480278015)]), id='00fe0c83-7386-457c-91d0-dc8ef2aa5ea5', block_type='LAYOUT_FIGURE', relationships=None, confidence=84.08203125, text=None, column_index=None, column_span=None, entity_types=None, page=2, row_index=None, row_span=None, selection_status=None, text_type=None, custom=None, query=None)
INFO       2023-11-25 11:07:00,316 textractprettyprinter.t_pretty_print_layout get_layout_csv_from_trp2             307 : layout_block_rel is None: TBlock(geometry=TGeometry(bounding_box=TBoundingBox(width=0.014714780263602734, height=0.011376634240150452, left=0.5052229762077332, top=0.3734390139579773), polygon=[TPoint(x=0.5052229762077332, y=0.3734619915485382), TPoint(x=0.519919753074646, y=0.3734390139579773), TPoint(x=0.5199377536773682, y=0.3847927153110504), TPoint(x=0.5052409172058105, y=0.38481566309928894)]), id='bef4df3e-732f-47b7-91da-76df04e25391', block_type='LAYOUT_FIGURE', relationships=None, confidence=33.59375, text=None, column_index=None, column_span=None, entity_types=None, page=2, row_index=None, row_span=None, selection_status=None, text_type=None, custom=None, query=None)
INFO       2023-11-25 11:07:00,316 textractprettyprinter.t_pretty_print_layout get_layout_csv_from_trp2             307 : layout_block_rel is None: TBlock(geometry=TGeometry(bounding_box=TBoundingBox(width=0.19598117470741272, height=0.08563102781772614, left=0.728996753692627, top=0.28380757570266724), polygon=[TPoint(x=0.728996753692627, y=0.28411757946014404), TPoint(x=0.924832284450531, y=0.28380757570266724), TPoint(x=0.9249779582023621, y=0.3691323399543762), TPoint(x=0.7291373610496521, y=0.3694385886192322)]), id='7c9d08db-a9cb-4229-b9b1-6c76166d7c98', block_type='LAYOUT_FIGURE', relationships=None, confidence=86.083984375, text=None, column_index=None, column_span=None, entity_types=None, page=2, row_index=None, row_span=None, selection_status=None, text_type=None, custom=None, query=None)

**Comment by anjanvb** [comment]
Ack... will take a look.

**Comment by anjanvb** [comment]
@schadem Issue fixed with PR - https://github.com/aws-samples/amazon-textract-textractor/pull/286

**Comment by anjanvb** [comment]
Closing since PR #286 was merged.
