### ISSUE TITLE
Confidence score output

### ISSUE THREAD

**Issue by kostabasis** [aws-samples/amazon-textract-textractor#295]
Is there a way to get confidence scores or image quality scores associated with each page, or layout element?

This is my current logic:

`from textractor.data.text_linearization_config import TextLinearizationConfig
from textractor import Textractor

extractor = Textractor(profile_name="default")

document = extractor.analyze_document(
file_source=png_path,
features=[TextractFeatures.TABLES, TextractFeatures.SIGNATURES, TextractFeatures.LAYOUT],
save_image=True
)

config = TextLinearizationConfig(
title_prefix="# ",
section_header_prefix="## ",
add_prefixes_and_suffixes_in_text=True,
heuristic_line_break_threshold=0.9,
heuristic_overlap_ratio=0.5,
table_linearization_format="markdown",
)
print(document.get_text(config=config))`

**Comment by Belval** [comment]
Confidence scores are not exposed in the Document entities but you should be able to access them using the `raw_object` like this `document.pages[0].tables[0].raw_object["Confidence"]`.

**Comment by kostabasis** [comment]
Nice, thanks!
