### ISSUE TITLE
start_document_analysis high memory usage

### ISSUE THREAD

**Issue by ttruong-gilead** [aws-samples/amazon-textract-textractor#316]
amazon-textract-caller==0.2.2
amazon-textract-response-parser==1.0.2
amazon-textract-textractor==1.7.4

Why is start_document_analysis() using so much memory? This is for pdfs of below 1000 pages.
Even with memory size of 32GB my container gets killed due to overloaded memory. Is there a leak?
Happens both locally and on ECS

I use the boto3 library with no issues on same pdfs. 

Usage: 
```
document = extractor.start_document_analysis(
                       file_source=TRIAL_DOCUMENT_S3_URI, 
                       features=[TextractFeatures.LAYOUT,TextractFeatures.TABLES],
                       s3_output_path=<some_s3_path>
                )
```

**Comment by Belval** [comment]
Hi!

Make sure to use `start_document_analysis` with `save_image=False` otherwise Textractor is pre-loading the images for visualizations which you likely do not care about.

Hopefully that is the issue.

**Comment by ttruong-gilead** [comment]
Indeed that's the issue. We do want to access page.image.size occassionally. There must be a better way of getting this per image instead of loading it all at once? Maybe store on disk. And also, why is save_image=True default?

**Comment by Belval** [comment]
You don't need to save the images to get the dimensions, you can use `page.height` and `page.width`. 

As for why it's the default, originally it was to match `analyze_document` and now it's to preserve backward compatibility, but I think I might add a warning for your use case.

**Comment by ttruong-gilead** [comment]
@Belval I'm closing this issue but I still think there needs to be a disk cache mechanism instead of saving it to memory for very large files.
