### ISSUE TITLE
[Feature Request] Caller to export useful constructs directly from the library root

### ISSUE THREAD

**Issue by athewsey** [aws-samples/amazon-textract-textractor#32]
IMO it's a bit verbose to have a submodule called `t_call` that contains basically all the useful parts of the (very small) `textractcaller` library.

Could we have the public members imported directly in `__init__`, so that you can e.g:

```python
from textractcaller import call_textract, OutputConfig, Textract_Features
```

?

**Comment by schadem** [comment]
Good suggestion, added them quickly and published a new version. Let me know when you face issues.
