### ISSUE TITLE
[Q] hide_keyavlue_layout option in TextLinearizationConfig

### ISSUE THREAD

**Issue by eml-39502** [aws-samples/amazon-textract-textractor#323]
# Inquiry

Please advise if it is possible to add ```hide_keyavlue_layout``` option to hide the KeyValue layouts. Currently the layout.py does not have such an option.

[layout.py](https://github.com/aws-samples/amazon-textract-textractor/blob/029c21fd621a5897c475b091899bfa8225ecea9d/textractor/entities/layout.py#L107-L114)

```
        if (
            (self.layout_type == LAYOUT_HEADER and config.hide_header_layout)
            or (self.layout_type == LAYOUT_FOOTER and config.hide_footer_layout)
            or (self.layout_type == LAYOUT_FIGURE and config.hide_figure_layout)
            or (self.layout_type == LAYOUT_PAGE_NUMBER and config.hide_page_num_layout)
            or (self.layout_type == LAYOUT_TABLE and config.hide_table_layout)
        ):
            return "", []
```

The intention is to extract only the text sentences from a document by omitting non textual element e.g. tables, forms, figures.

If there is an alternative, kindly advise.

**Comment by Belval** [comment]
Hi, we can definitely add a `hide_key_value_layout` configuration option, but I would like to make sure that this will have the intended result for your use case.

"Hiding" removes the layout and its words from the `.get_text()` output. If you have a KEY_VALUE_SET detected in your document, it will not be part of the output at all.

**Comment by eml-39502** [comment]
Yes, I would like to remove LAYOUT_KEY_VALUE elements from the document.get_text(config=config) or page.get_text(config=config) outputs.

**Comment by eml-39502** [comment]
Thank you.
