### ISSUE TITLE
prefix and suffix for footer layout is not available

### ISSUE THREAD

**Issue by LeoHemamou** [aws-samples/amazon-textract-textractor#365]
In the config file `from textractor.data.text_linearization_config import TextLinearizationConfig` , I can't add tags (prefix and suffix) for footer layout part as it seems not implemented . Is it a normal behavior or a missing part ?

Best

**Comment by Belval** [comment]
This is fixed in 1.8.2.

https://github.com/aws-samples/amazon-textract-textractor/blob/master/textractor/data/text_linearization_config.py#L160
