### ISSUE TITLE
The invoice number won’t be detected if there is no space between the label and the value

### ISSUE THREAD

**Issue by arsher-b** [aws-samples/amazon-textract-textractor#397]
The invoice number was not detected. We assume this is because there is no space between the label and the value. 
This issue occurs in both the Amazon Textract console and the amazon-textract-textractor.
![image](https://github.com/user-attachments/assets/99e00bc1-4069-4bb4-b1ab-244879c21e2f)
![image](https://github.com/user-attachments/assets/0415ff2e-037b-457a-945f-85f3885a48f0)

Expected Output: The INVOICE# value is detected.
`INVOICE# = 001-000203672`
`INVOICE# = 005-000228722`

Sample Receipt:
![11 (1)](https://github.com/user-attachments/assets/1b6c4ffd-c87b-4d54-8c2f-ec6d3aae1c2e)
![17](https://github.com/user-attachments/assets/746cf2c9-aa73-4635-b1a0-8801bc18c38c)

**Comment by Belval** [comment]
Hi @arsher-b, when an issue is reproducible in both Textractor in the console, I would advise to raise it with customer support and not on the GitHub package. These issues are coming from the Textract service itself and as such cannot be fixed by Textractor which is a parsing library.
