### ISSUE TITLE
KeyError: 'Relationships'

### ISSUE THREAD

**Issue by lucio-xelda** [aws-samples/amazon-textract-textractor#406]
We are facing a `KeyError: 'Relationships'` error processing a specific document. Unfortunately, given the private nature of the document, I am won't be able to share it.

The full stack trace of the error is reported below:

```
"stack_trace": {
        "type": "KeyError",
        "value": "'Relationships'",
        "module": "builtins",
        "frames": [
            {
                "file": "/var/task/chalicelib/clients/textract.py",
                "line": 51,
                "function": "extract_text",
                "statement": "document = response_parser.parse(paginated_response)"
            },
            {
                "file": "/var/task/textractor/parsers/response_parser.py",
                "line": 1562,
                "function": "parse",
                "statement": "return parse_document_api_response(converter(response))"
            },
            {
                "file": "/var/task/textractor/utils/legacy_utils.py",
                "line": 42,
                "function": "converter",
                "statement": "for relationship in page_block[\"Relationships\"]:"
            }
        ]
    }, 
```

The `/var/task/chalicelib/clients/textract.py` is running the following simplified code:

[[REDACTED]]

**Comment by Belval** [comment]
This is an edge case in the legacy parser that was added in 1.8.4, I will issue a fix in the next hour but in the meantime downgrading to 1.8.3 will fix it.

**Comment by Belval** [comment]
Fixed by [0db2f94](https://github.com/aws-samples/amazon-textract-textractor/commit/0db2f9444a603d246656f31f255387a0356ab37f)

**Comment by lucio-xelda** [comment]
Thanks Belval for the quick fix!

Will you release a new version with the fix soon?

**Comment by Belval** [comment]
Version 1.8.5 should be available in PyPI, let me know if the issue is properly fixed.

**Comment by lucio-xelda** [comment]
All good.
I am not able to replicate the issue with 1.8.5.
Thanks again!
