### ISSUE TITLE
PDF must be in S3 bucket?

### ISSUE THREAD

**Issue by yosefvb** [aws-samples/amazon-textract-textractor#5]
When running the following command:

`python3 textractor.py --documents document-name.pdf --text --forms --tables`

I get an error `Exception: PDF must be in S3 bucket`. Can it not be run on a local document?

Full error message below:

>Traceback (most recent call last):
  File "textractor.py", line 164, in <module>
    Textractor().run()
  File "textractor.py", line 143, in run
    self.processDocument(ips, i, document)
  File "textractor.py", line 98, in processDocument
    dp = DocumentProcessor(ips["bucketName"], document, ips["awsRegion"], ips["text"], ips["forms"], ips["tables"])
  File "/mnt/c/Users/Username/Documents/textractor/tdp.py", line 218, in __init__
    raise Exception("PDF must be in S3 bucket.")
Exception: PDF must be in S3 bucket.

**Comment by darwaishx** [comment]
Textract async API expect PDF as an S3 object. 

Example below show how to take a PDF on local disk, extract individual images and process them.
https://github.com/aws-samples/amazon-textract-searchable-pdf/blob/master/src/SearchablePDF/src/main/java/DemoPdfFromLocalPdf.java

**Comment by yosefvb** [comment]
Thanks @darwaishx ! It would be great to add this to the READ.me to clarify to future users.

**Comment by ocelotsloth** [comment]
Yeah @darwaishx that README is pretty confusing...at least it got me on this same issue as well.

There are a couple sections in particular:

> - python3 textractor.py --documents [file|folder|S3Object|S3Folder] --text --forms --tables --region [AWSRegion] --insights --medical-insights --translate [LanguageCode]

>   | Argument  | Description |
>  | ------------- | ------------- |
>  | --documents  | Name of the document or local folder/S3 bucket |

which seem to reference the ability for this script to accept local files directly.

**Comment by jostradamus** [comment]
@darwaishx
I'm afraid that this is not a proper resolution or closure of this issue.  It makes no explanation as to why the instructions state "query S3 **or local folder** to get input documents", yet it will not actually accept a local folder or file.  

Nor does the response explain how to use the java file.

**Comment by grantrosse** [comment]
Ran into this as well, send the PDF as bytes instead:

```
file_name = 'Invoice_INV300351.pdf'
client = boto3.client('textract', 'us-east-1')
with open(file_name, "rb") as sample_file:
    b = bytearray(sample_file.read())
response = call_textract(input_document=b, boto3_textract_client=client )
pickle.dump(response, open(f'response_{file_name.split(".")[0]}.pk', 'wb')) 
```

**Comment by grantrosse** [comment]
Yeah for sure @schadem https://github.com/aws-samples/amazon-textract-textractor/issues/236
