### ISSUE TITLE
Breaking compatibility requirement

### ISSUE THREAD

**Issue by kgont** [aws-samples/amazon-textract-textractor#61]
Hi I am happy amazon-textract-caller user, 
after updating to latest version difficulties with dependencies appeared:

https://github.com/aws-samples/amazon-textract-textractor/blob/master/caller/textractcaller/t_call.py#L11
line unused, breaks compatibility with previous requirements, provides marshmallow package into dependencies base, please verify

**Comment by schadem** [comment]
Thx for reporting. Fixed in amazon-textract-caller 0.0.17.
