### ISSUE TITLE
Invalid input: Document or path to a foler or S3 bucket containing documents is required.

### ISSUE THREAD

**Issue by camiwins** [aws-samples/amazon-textract-textractor#7]
Hello - I'm running into errors when trying to process a PDF on my S3 bucket. 

First thing I did was reference the ReadMe and tried the following:

`py textractor.py --documents s3://bucketname/filename.pdf --text --forms --tables`

Error I received:

`Invalid input: An error occurred (InvalidToken) when calling the GetBucketLocation operation: The provided token is malformed or otherwise invalid.
Valid format:
- python3 textractor.py --documents mydoc.jpg --text --forms --tables --region us-east-1
- python3 textractor.py --documents ./myfolder/ --text --forms --tables
- python3 textractor.py --document s3://mybucket/mydoc.pdf --text --forms --tables
- python3 textractor.py --document s3://mybucket/ --text --forms --tables
Traceback (most recent call last):
  File "textractor.py", line 164, in <module>
    Textractor().run()
  File "textractor.py", line 135, in run
    totalDocuments = len(ips["documents"])
TypeError: 'NoneType' object is not subscriptable`

I noticed there's no "s" when trying to process a file on s3, so I tried this:

`py textractor.py --document s3://bucketname/filename.pdf --text --forms --tables`

Got this error:

Invalid input: Document or path to a foler or S3 bucket containing documents is required.
Valid format:
- python3 textractor.py --documents mydoc.jpg --text --forms --tables --region us-east-1
- python3 textractor.py --documents ./myfolder/ --text --forms --tables
- python3 textractor.py --document s3://mybucket/mydoc.pdf --text --forms --tables
- python3 textractor.py --document s3://mybucket/ --text --forms --tables
Traceback (most recent call last):
  File "textractor.py", line 164, in <module>
    Textractor().run()
  File "textractor.py", line 135, in run
    totalDocuments = len(ips["documents"])
TypeError: 'NoneType' object is not subscriptable

Additionally... I tried running a test file locally (I chose a JPG and not a PDF since I get another message when trying to process a PDF locally stating I need to upload the PDF to an S3 bucket)

`py textractor.py --documents test.jpg --text`

And it seemed to work but ended up getting an error:

Textracting Document # 1: test.jpg
Calling Textract...
Traceback (most recent call last):
  File "textractor.py", line 164, in <module>
    Textractor().run()
  File "textractor.py", line 143, in run
    self.processDocument(ips, i, document)
  File "textractor.py", line 99, in processDocument
    response = dp.run()
  File "C:\Users\CamiLaPorte\Desktop\Checkbox-Textract\amazon-textract-textractor\src\tdp.py", line 232, in run
    response = ip.run()
  File "C:\Users\CamiLaPorte\Desktop\Checkbox-Textract\amazon-textract-textractor\src\tdp.py", line 79, in run
    response = self._callTextract()
  File "C:\Users\CamiLaPorte\Desktop\Checkbox-Textract\amazon-textract-textractor\src\tdp.py", line 42, in _callTextract
    response = textract.detect_document_text(Document={'Bytes': imageBytes})
  File "C:\Users\CamiLaPorte\Anaconda3\lib\site-packages\botocore\client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\CamiLaPorte\Anaconda3\lib\site-packages\botocore\client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the DetectDocumentText operation: The security token included in the request is invalid

I've used textractor code multiple times in the last year and have never had this issue. It's only been with a recent download of the repo and code that I'm experiencing this. There have been no changes to my machine and I'm running the same environments (I've even tried multiple environments as well.)

Please let me know if you need more information. Thanks!

**Comment by alxalmora** [comment]
Got same problem.

> I noticed there's no "s" when trying to process a file on s3, so I tried this:
> `py textractor.py --document s3://bucketname/filename.pdf --text --forms --tables`

--document is a typo, the correct argument is `documents`

After 6 or 7 tries, it works. I'm using EC2 environment to connect my own S3 bucket, I think that error is about tokens in AWS CLI. The documentation for Textract is horrible.

**Comment by darwaishx** [comment]
Issue has been fixed. tdp.py was returns None if job is not successful which was causing response processor to throw exception.
