### ISSUE TITLE
support single page PDF

### ISSUE THREAD

**Issue by schadem** [aws-samples/amazon-textract-textractor#77]
Textrat launched single page PDF, should be supported in the caller.
Currently PDF defaults to async - we dont' want to change that. Maybe add a force_sync param to the method.
﻿

**Comment by schadem** [comment]
https://docs.aws.amazon.com/textract/latest/dg/sync-calling.html

**Comment by tb102122** [comment]
I would suggest to have a mode parameter with the options sync, asycn, default
the default behavior would like what the APIs support single page pdf (evaluation would be added before) as sync and pictures. For sync and asycn it would go directly to the related API call and if a multi page pdf is send than we get the default API error. 
In that way I think we can have the most flexibility of the caller module.

**Comment by tb102122** [comment]
@schadem What do you think about the suggested approach?

**Comment by schadem** [comment]
I like the mode parameter. I think we should add an option to have the caller decide what is 'best' based on the number of pages, but that requires to calculate the page numbers, which in turn requires additional libraries which I don't want to pull into this lightweight component. We could have them as optional install components though.

**Comment by tb102122** [comment]
@schadem yes I know what you mean. What about having the mode parameter as optional parameter with the possible values "**best**", "sync" and "async" and in case the mode parameter is available the additional libs are imported. That would still add the dependency of the libs to the overall package but makes the startup lightweight in case you don't need the option.
