### ISSUE TITLE
How can I order the results as shown in the pdf?

### ISSUE THREAD

**Issue by robertdac** [aws-samples/amazon-textract-textractor#85]
PDF

![Captura de pantalla de 2022-05-05 15-38-43](https://user-images.githubusercontent.com/8030118/166937006-b560ace3-071d-4b15-81e7-555e32aba8ce.png)

Example :
python3 textractor.py --documents s3://mybucket/mydoc.pdf  --forms 

Result :

62692bb61ab53-pdf-page-1-forms.csv

![Captura de pantalla de 2022-05-05 16-00-35](https://user-images.githubusercontent.com/8030118/166939976-90322dc4-d90a-479d-bb52-d5e19f82c8da.png)

how can i order this way

![Captura de pantalla de 2022-05-05 16-04-33](https://user-images.githubusercontent.com/8030118/166941481-ece38216-fc6c-469f-8102-e03245d3b111.png)

**Comment by tb102122** [comment]
@robertdac Can you share some more details and maybe you sample code. What kind of ordering do you like to apply?

Cheers Tobias

**Comment by tb102122** [comment]
Did you check the output like described on the page [https://github.com/aws-samples/amazon-textract-textractor](url)
"document-page-n-text-inreadingorder.txt: Detected text in reading order (multi-column) for each page in the document."

**Comment by syley** [comment]
Hi @tb102122 I'm facing a similar issue with key values exported as csv using a python script. 

The checkboxes and key values do not appear to be in any specific order. As there are quite a few duplicate checkboxes (e.g Yes/No) was hoping to be able to format if possible left to right, top to bottom.

`document = extractor.start_document_analysis(
    file_source=("Application Form trimmed.pdf"),
    features=[TextractFeatures.FORMS],
    s3_upload_path="s3://textractbucket2/"
)
document.export_kv_to_csv(
    include_kv=True,
    include_checkboxes=True,
    filepath="async_kv.csv"
)  `

**Comment by tb102122** [comment]
@syley that example should help you but in your case it sounds a but more complex. 
https://github.com/aws-samples/amazon-textract-textractor/blob/master/tpipelinegeofinder/geofinder-sample-notebook.ipynb
