### ISSUE TITLE
Can not force sync

### ISSUE THREAD

**Issue by schadem** [aws-samples/amazon-textract-textractor#93]
When sending in a document it is not clear if async or sync is called.
We can force async, but not sync.
Accidentially sending a multi page document when expecting sync calls can lead to timeouts and errors.
`

**Comment by tb102122** [comment]
That issue is based on my understanding related to the issue #77

**Comment by schadem** [comment]
Exactly. Let me add a fix.

**Comment by schadem** [comment]
Duplicate #77
